// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG8UrwRUidiNg8JpiUNmlLb1vyTTfgTEA',
    appId: '1:1033833723816:web:4a31b74d627e66afb34f9d',
    messagingSenderId: '1033833723816',
    projectId: 'e-commerece-app-31237',
    authDomain: 'e-commerece-app-31237.firebaseapp.com',
    storageBucket: 'e-commerece-app-31237.firebasestorage.app',
    measurementId: 'G-FKWJFJ10NB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7J28oB9zlRPL7kigP1w1NNqtOiTwXs_Y',
    appId: '1:1033833723816:android:e884d62c6d7aa8a7b34f9d',
    messagingSenderId: '1033833723816',
    projectId: 'e-commerece-app-31237',
    storageBucket: 'e-commerece-app-31237.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKMkdSkS-y5ZKnyHcOyb5k-Qir7UF8lXM',
    appId: '1:1033833723816:ios:5e2f5f6c04c50747b34f9d',
    messagingSenderId: '1033833723816',
    projectId: 'e-commerece-app-31237',
    storageBucket: 'e-commerece-app-31237.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKMkdSkS-y5ZKnyHcOyb5k-Qir7UF8lXM',
    appId: '1:1033833723816:ios:5e2f5f6c04c50747b34f9d',
    messagingSenderId: '1033833723816',
    projectId: 'e-commerece-app-31237',
    storageBucket: 'e-commerece-app-31237.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG8UrwRUidiNg8JpiUNmlLb1vyTTfgTEA',
    appId: '1:1033833723816:web:c00074274f1b8b29b34f9d',
    messagingSenderId: '1033833723816',
    projectId: 'e-commerece-app-31237',
    authDomain: 'e-commerece-app-31237.firebaseapp.com',
    storageBucket: 'e-commerece-app-31237.firebasestorage.app',
    measurementId: 'G-MZVK4X8537',
  );
}
